-- auto-generated by plugins/floating_rules.lua
-- do not edit while somewm is running; additions via Super+Alt+F are persisted here
return {
    class = { "Arandr", "Blueman-manager", "Lxappearance", "Gsmartcontrol", "hp-toolbox", "Protonvpn-gui", "Syncthing GTK", "netctl-gui", "Solaar", "Font-manager", "Font Manager", "qt5ct", "Deskflow", "Cadence", "qjackctl", "Studio-controls", "QjackCtl", "kmix", "Pavucontrol", "pwvucontrol", "Goodvibes", "Drumstick MIDI Monitor", "Audio/MIDI Setup", "Mixer", "seq64", "qseq66", "patroneo", "Agordejo", "radium_compessor", "Vlc", "vokoscreenNG", "SimpleScreenRecorder", "Indicator-sound-switcher5", "Gpick", "Kruler", "emulsion", "Sxiv", "qimgv", "qView", "Image Lounge", "Image Menu", "spectacle", "Tor Browser", "MessageWin", "copyq", "* Copying", "krunner", "xtightvncviewer", "scrcpy", "Gnaural", "kdeconnect.sms", "Mattermost", "Onboard", "gammy", "Flirc", "isoimagewriter", "Xdotoolgui.py", "mpd218 editor.exe", "Indicator-sound-switcher", "easyeffects", "blueman-manager", "xdg-desktop-portal-gtk", "pavucontrol", },
    instance = { "DTA", "copyq", "pinentry", "ncmpcpp", },
    name = { "Event Tester", "Choose an application", "File operations", "Blender Preferences", "Options", "Tree View Menu", "menu", },
    role = { "AlarmWindow", "ConfigManager", "pop-up", "page-info", "TfrmFileOp", "TfrmViewer", },
}
