return {
  ["Mod4|F8"] = {
    count = 0,
    key = "F8",
    mods = "Mod4",
    desc = "run keepassxc",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|F12"] = {
    count = 0,
    key = "F12",
    mods = "Mod4+Shift",
    desc = "run Chromium",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|t"] = {
    count = 0,
    key = "t",
    mods = "Control+Mod4",
    desc = "toggle tasklist filter (currenttags/alltags)",
    group = "awesome",
    first_seen = 1757200286,
    last_seen = 0,
  },
  ["Mod4|#16"] = {
    count = 0,
    key = "#16",
    mods = "Mod4",
    desc = "view tag #7",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#16"] = {
    count = 0,
    key = "#16",
    mods = "Mod1+Mod4",
    desc = "toggle tag #7",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#21"] = {
    count = 0,
    key = "#21",
    mods = "Mod1+Mod4",
    desc = "toggle tag #12",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4|k"] = {
    count = 0,
    key = "k",
    mods = "Control+Mod1+Mod4",
    desc = "Change screen to the k",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod4+Shift|m"] = {
    count = 0,
    key = "m",
    mods = "Mod4+Shift",
    desc = "(un)maximize horizontally",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#16"] = {
    count = 0,
    key = "#16",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #7",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1|Tab"] = {
    count = 3,
    key = "Tab",
    mods = "Mod1",
    desc = "cycle through clients",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757181087,
  },
  ["Mod1+Mod4|c"] = {
    count = 0,
    key = "c",
    mods = "Mod1+Mod4",
    desc = "colour picker to clipboard",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Shift|h"] = {
    count = 0,
    key = "h",
    mods = "Control+Mod1+Shift",
    desc = "Move tag to the h",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod4|z"] = {
    count = 18,
    key = "z",
    mods = "Mod4",
    desc = "toggle floating",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757216171,
  },
  ["Control+Mod4+Shift|#12"] = {
    count = 0,
    key = "#12",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #3",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|j"] = {
    count = 0,
    key = "j",
    mods = "Control+Mod4",
    desc = "focus the next screen",
    group = "screen",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|p"] = {
    count = 0,
    key = "p",
    mods = "Mod4",
    desc = "run pavucontrol",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#13"] = {
    count = 0,
    key = "#13",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #4",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|space"] = {
    count = 13,
    key = "space",
    mods = "Mod4",
    desc = "run rofi app launcher",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757306546,
  },
  ["Control+Mod4|l"] = {
    count = 2,
    key = "l",
    mods = "Control+Mod4",
    desc = "decrease the number of columns",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757163809,
  },
  ["Mod4|F1"] = {
    count = 0,
    key = "F1",
    mods = "Mod4",
    desc = "run ncmpcpp in a terminal",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#20"] = {
    count = 0,
    key = "#20",
    mods = "Mod4",
    desc = "view tag #11",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|m"] = {
    count = 20,
    key = "m",
    mods = "Mod4",
    desc = "(un)maximize",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757216014,
  },
  ["Control+Mod1|h"] = {
    count = 0,
    key = "h",
    mods = "Control+Mod1",
    desc = "Select tag to the h",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod4|Escape"] = {
    count = 0,
    key = "Escape",
    mods = "Mod4",
    desc = "go back",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4|j"] = {
    count = 0,
    key = "j",
    mods = "Control+Mod1+Mod4",
    desc = "Change screen to the j",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod1+Mod4|#19"] = {
    count = 1,
    key = "#19",
    mods = "Mod1+Mod4",
    desc = "toggle tag #10",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 1757165779,
  },
  ["Control+Mod1+Mod4+Shift|j"] = {
    count = 0,
    key = "j",
    mods = "Control+Mod1+Mod4+Shift",
    desc = "Move tag screen to the j",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4|r"] = {
    count = 0,
    key = "r",
    mods = "Control+Mod1+Mod4",
    desc = "Denon amp power toggle",
    group = "hotkeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#11"] = {
    count = 0,
    key = "#11",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #2",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#10"] = {
    count = 0,
    key = "#10",
    mods = "Mod1+Mod4",
    desc = "toggle tag #1",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#18"] = {
    count = 1,
    key = "#18",
    mods = "Mod4",
    desc = "view tag #9",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 1757296346,
  },
  ["Mod1+Mod4|space"] = {
    count = 6,
    key = "space",
    mods = "Mod1+Mod4",
    desc = "run rofi cmd launcher",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757279252,
  },
  ["Mod4|r"] = {
    count = 20,
    key = "r",
    mods = "Mod4",
    desc = "select next layout",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757306548,
  },
  ["Mod4+Shift|q"] = {
    count = 0,
    key = "q",
    mods = "Mod4+Shift",
    desc = "quit awesome",
    group = "awesome",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|k"] = {
    count = 8,
    key = "k",
    mods = "Mod4",
    desc = "focus previous by index",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757207027,
  },
  ["Control+Mod4+Shift|#11"] = {
    count = 0,
    key = "#11",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #2",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|Print"] = {
    count = 1,
    key = "Print",
    mods = "Mod4",
    desc = "take a screenshot with Flameshot",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757210542,
  },
  ["Mod4|F2"] = {
    count = 1,
    key = "F2",
    mods = "Mod4",
    desc = "run RaySession",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757207470,
  },
  ["Control+Mod4+Shift|#21"] = {
    count = 0,
    key = "#21",
    mods = "Control+Mod4+Shift",
    desc = "toggle client on tag #12",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|F9"] = {
    count = 0,
    key = "F9",
    mods = "Mod4",
    desc = "run doublecmd",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|;"] = {
    count = 3,
    key = ";",
    mods = "Mod1+Mod4",
    desc = "restore all minimized windows",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757206985,
  },
  ["Control+Mod4+Shift|Left"] = {
    count = 0,
    key = "Left",
    mods = "Control+Mod4+Shift",
    desc = "view previous",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["|XF86AudioPause"] = {
    count = 0,
    key = "XF86AudioPause",
    mods = "",
    desc = "media pause",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#18"] = {
    count = 0,
    key = "#18",
    mods = "Control+Mod4",
    desc = "toggle tag #9",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|q"] = {
    count = 0,
    key = "q",
    mods = "Mod1+Mod4",
    desc = "xkill to kill a hung GUI app",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|c"] = {
    count = 0,
    key = "c",
    mods = "Control+Mod4",
    desc = "media pause",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|e"] = {
    count = 0,
    key = "e",
    mods = "Mod4+Shift",
    desc = "edit wm config",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4+Shift|k"] = {
    count = 0,
    key = "k",
    mods = "Control+Mod1+Mod4+Shift",
    desc = "Move tag screen to the k",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod1+Mod4|#17"] = {
    count = 0,
    key = "#17",
    mods = "Mod1+Mod4",
    desc = "toggle tag #8",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|h"] = {
    count = 0,
    key = "h",
    mods = "Control+Mod4+Shift",
    desc = "",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod4|#17"] = {
    count = 0,
    key = "#17",
    mods = "Mod4",
    desc = "view tag #8",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#14"] = {
    count = 0,
    key = "#14",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #5",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|Right"] = {
    count = 7,
    key = "Right",
    mods = "Mod4",
    desc = "cycle to next tag with clients",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 1757163927,
  },
  ["Mod4+Shift|Return"] = {
    count = 0,
    key = "Return",
    mods = "Mod4+Shift",
    desc = "open floating terminal",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#17"] = {
    count = 0,
    key = "#17",
    mods = "Control+Mod4",
    desc = "toggle tag #8",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#15"] = {
    count = 0,
    key = "#15",
    mods = "Mod4",
    desc = "view tag #6",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|w"] = {
    count = 0,
    key = "w",
    mods = "Mod4+Shift",
    desc = "ontop floating right corner (smart)",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|Right"] = {
    count = 0,
    key = "Right",
    mods = "Control+Mod4+Shift",
    desc = "view next",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#12"] = {
    count = 0,
    key = "#12",
    mods = "Mod1+Mod4",
    desc = "toggle tag #3",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|v"] = {
    count = 52,
    key = "v",
    mods = "Mod1+Mod4",
    desc = "switch to vertical treetile layout",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757168844,
  },
  ["Control+Mod4|i"] = {
    count = 1,
    key = "i",
    mods = "Control+Mod4",
    desc = "toggle layout icon pack (png/svg)",
    group = "awesome",
    first_seen = 1757180776,
    last_seen = 1757285256,
  },
  ["Control+Mod4|a"] = {
    count = 1,
    key = "a",
    mods = "Control+Mod4",
    desc = "run arandr",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757205353,
  },
  ["Mod4+Shift|F4"] = {
    count = 0,
    key = "F4",
    mods = "Mod4+Shift",
    desc = "run simplescreenrecorder",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|r"] = {
    count = 2,
    key = "r",
    mods = "Mod4+Shift",
    desc = "select previous layout",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757162388,
  },
  ["Mod1+Mod4|#14"] = {
    count = 0,
    key = "#14",
    mods = "Mod1+Mod4",
    desc = "toggle tag #5",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|space"] = {
    count = 2,
    key = "space",
    mods = "Mod4+Shift",
    desc = "show the menubar",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757281124,
  },
  ["Mod4|#11"] = {
    count = 0,
    key = "#11",
    mods = "Mod4",
    desc = "view tag #2",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["|XF86AudioRaiseVolume"] = {
    count = 0,
    key = "XF86AudioRaiseVolume",
    mods = "",
    desc = "increase volume",
    group = "hotkeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|'"] = {
    count = 0,
    key = "'",
    mods = "Mod1+Mod4",
    desc = "cycle minimized windows (current screen)",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|a"] = {
    count = 0,
    key = "a",
    mods = "Mod4",
    desc = "large centre floating window",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#12"] = {
    count = 0,
    key = "#12",
    mods = "Control+Mod4",
    desc = "toggle tag #3",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4|h"] = {
    count = 0,
    key = "h",
    mods = "Control+Mod1+Mod4",
    desc = "open Hue lighting media sync",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|l"] = {
    count = 0,
    key = "l",
    mods = "Mod1+Mod4",
    desc = "Resize to the l",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["|XF86AudioLowerVolume"] = {
    count = 0,
    key = "XF86AudioLowerVolume",
    mods = "",
    desc = "decrease volume",
    group = "hotkeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#19"] = {
    count = 0,
    key = "#19",
    mods = "Mod4+Shift",
    desc = "move client and follow to tag #10",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|w"] = {
    count = 26,
    key = "w",
    mods = "Mod4",
    desc = "close window",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757286806,
  },
  ["Control+Mod4|h"] = {
    count = 2,
    key = "h",
    mods = "Control+Mod4",
    desc = "increase the number of columns",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757163810,
  },
  ["Control+Mod1+Mod4|l"] = {
    count = 0,
    key = "l",
    mods = "Control+Mod1+Mod4",
    desc = "Change screen to the l",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Control+Mod4|#21"] = {
    count = 0,
    key = "#21",
    mods = "Control+Mod4",
    desc = "move client to tag #12",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|k"] = {
    count = 0,
    key = "k",
    mods = "Mod1+Mod4",
    desc = "rotate screens right",
    group = "screen",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|Tab"] = {
    count = 0,
    key = "Tab",
    mods = "Control+Mod4+Shift",
    desc = "cycle backward through clients (super+ctrl)",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4|v"] = {
    count = 0,
    key = "v",
    mods = "Control+Mod1+Mod4",
    desc = "Denon amp mute toggle",
    group = "hardware",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|x"] = {
    count = 4,
    key = "x",
    mods = "Mod4",
    desc = "toggle sticky",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757216164,
  },
  ["Mod4+Shift|#15"] = {
    count = 0,
    key = "#15",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #6",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|f"] = {
    count = 0,
    key = "f",
    mods = "Control+Mod4+Shift",
    desc = "add focused window to floating rules",
    group = "awesome",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["|XF86MonBrightnessDown"] = {
    count = 0,
    key = "XF86MonBrightnessDown",
    mods = "",
    desc = "decrease brightness",
    group = "hotkeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4+Shift|4"] = {
    count = 0,
    key = "4",
    mods = "Mod1+Mod4+Shift",
    desc = "border sync shimmer mode",
    group = "shimmer",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|Left"] = {
    count = 7,
    key = "Left",
    mods = "Mod4",
    desc = "cycle to previous tag with clients",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 1757163930,
  },
  ["Mod4+Shift|#20"] = {
    count = 0,
    key = "#20",
    mods = "Mod4+Shift",
    desc = "move client and follow to tag #11",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|comma"] = {
    count = 0,
    key = "comma",
    mods = "Mod4",
    desc = "behind",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|o"] = {
    count = 0,
    key = "o",
    mods = "Mod4",
    desc = "move to screen",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#11"] = {
    count = 0,
    key = "#11",
    mods = "Control+Mod4",
    desc = "toggle tag #2",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|Left"] = {
    count = 0,
    key = "Left",
    mods = "Mod1+Mod4",
    desc = "view previous non-empty tag",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|F3"] = {
    count = 0,
    key = "F3",
    mods = "Mod4",
    desc = "run qBittorrent",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#10"] = {
    count = 0,
    key = "#10",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #1",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|w"] = {
    count = 0,
    key = "w",
    mods = "Control+Mod4+Shift",
    desc = "ontop floating right corner (manual)",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4+Shift|l"] = {
    count = 0,
    key = "l",
    mods = "Control+Mod1+Mod4+Shift",
    desc = "Move tag screen to the l",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Control+Mod4|x"] = {
    count = 0,
    key = "x",
    mods = "Control+Mod4",
    desc = "media play",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#21"] = {
    count = 0,
    key = "#21",
    mods = "Mod4+Shift",
    desc = "move client and follow to tag #12",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#15"] = {
    count = 0,
    key = "#15",
    mods = "Mod1+Mod4",
    desc = "toggle tag #6",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|f"] = {
    count = 2,
    key = "f",
    mods = "Mod4",
    desc = "toggle fullscreen",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757216017,
  },
  ["|XF86AudioStop"] = {
    count = 0,
    key = "XF86AudioStop",
    mods = "",
    desc = "media stop",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|u"] = {
    count = 0,
    key = "u",
    mods = "Mod4",
    desc = "jump to urgent client",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|k"] = {
    count = 0,
    key = "k",
    mods = "Control+Mod4+Shift",
    desc = "",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod4+Shift|F6"] = {
    count = 0,
    key = "F6",
    mods = "Mod4+Shift",
    desc = "run qseq66",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|k"] = {
    count = 0,
    key = "k",
    mods = "Mod4+Shift",
    desc = "swap with previous client by index",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|l"] = {
    count = 13,
    key = "l",
    mods = "Mod4",
    desc = "increase master width factor",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757207030,
  },
  ["Control+Mod4|n"] = {
    count = 0,
    key = "n",
    mods = "Control+Mod4",
    desc = "restore minimized",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["|XF86AudioPlay"] = {
    count = 0,
    key = "XF86AudioPlay",
    mods = "",
    desc = "media play",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#18"] = {
    count = 0,
    key = "#18",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #9",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|F11"] = {
    count = 0,
    key = "F11",
    mods = "Mod4",
    desc = "run quasselclient",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|F1"] = {
    count = 0,
    key = "F1",
    mods = "Mod4+Shift",
    desc = "run Spotify",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#15"] = {
    count = 0,
    key = "#15",
    mods = "Control+Mod4",
    desc = "toggle tag #6",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1|l"] = {
    count = 0,
    key = "l",
    mods = "Control+Mod1",
    desc = "Select tag to the l",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod4|s"] = {
    count = 0,
    key = "s",
    mods = "Mod4",
    desc = "show help",
    group = "awesome",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|space"] = {
    count = 0,
    key = "space",
    mods = "Control+Mod4",
    desc = "toggle floating",
    group = "client",
    first_seen = 1757206220,
    last_seen = 0,
  },
  ["Control+Mod4|left"] = {
    count = 0,
    key = "left",
    mods = "Control+Mod4",
    desc = "move client to prev tag",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|slash"] = {
    count = 0,
    key = "slash",
    mods = "Mod4",
    desc = "above",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["|XF86BrightnessUp"] = {
    count = 0,
    key = "XF86BrightnessUp",
    mods = "",
    desc = "increase brightness",
    group = "hotkeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|c"] = {
    count = 0,
    key = "c",
    mods = "Mod4+Shift",
    desc = "close",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|v"] = {
    count = 1,
    key = "v",
    mods = "Control+Mod4",
    desc = "media next",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 1757168862,
  },
  ["Mod1+Mod4+Shift|5"] = {
    count = 0,
    key = "5",
    mods = "Mod1+Mod4+Shift",
    desc = "deep gold shimmer mode",
    group = "shimmer",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#13"] = {
    count = 0,
    key = "#13",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #4",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|Right"] = {
    count = 0,
    key = "Right",
    mods = "Mod1+Mod4",
    desc = "view next non-empty tag",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|b"] = {
    count = 0,
    key = "b",
    mods = "Control+Mod4",
    desc = "blank screen(s) temporarily",
    group = "awesome",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4+Shift|2"] = {
    count = 0,
    key = "2",
    mods = "Mod1+Mod4+Shift",
    desc = "cloud shimmer mode",
    group = "shimmer",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|Return"] = {
    count = 27,
    key = "Return",
    mods = "Mod4",
    desc = "open terminal",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757286832,
  },
  ["Control+Mod4+Shift|q"] = {
    count = 0,
    key = "q",
    mods = "Control+Mod4+Shift",
    desc = "Confirm Awesome wm exit",
    group = "awesome",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|h"] = {
    count = 17,
    key = "h",
    mods = "Mod4",
    desc = "decrease master width factor",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757308278,
  },
  ["Control+Mod4|Tab"] = {
    count = 0,
    key = "Tab",
    mods = "Control+Mod4",
    desc = "cycle through clients (super+ctrl)",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4+Shift|1"] = {
    count = 0,
    key = "1",
    mods = "Mod1+Mod4+Shift",
    desc = "candle shimmer mode",
    group = "shimmer",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|l"] = {
    count = 0,
    key = "l",
    mods = "Control+Mod4+Shift",
    desc = "",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|j"] = {
    count = 0,
    key = "j",
    mods = "Control+Mod4+Shift",
    desc = "",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Control+Mod4|#19"] = {
    count = 0,
    key = "#19",
    mods = "Control+Mod4",
    desc = "move client to tag #10",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#13"] = {
    count = 0,
    key = "#13",
    mods = "Control+Mod4",
    desc = "toggle tag #4",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|F4"] = {
    count = 0,
    key = "F4",
    mods = "Mod4",
    desc = "run picard",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|right"] = {
    count = 0,
    key = "right",
    mods = "Control+Mod4",
    desc = "move client to next tag without follow",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|d"] = {
    count = 0,
    key = "d",
    mods = "Control+Mod4",
    desc = "media stop",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#17"] = {
    count = 0,
    key = "#17",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #8",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|j"] = {
    count = 5,
    key = "j",
    mods = "Mod4",
    desc = "focus next by index",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757296362,
  },
  ["Mod1+Shift|Tab"] = {
    count = 0,
    key = "Tab",
    mods = "Mod1+Shift",
    desc = "cycle backward through clients",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|n"] = {
    count = 6,
    key = "n",
    mods = "Mod4",
    desc = "minimize",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757199499,
  },
  ["Mod4+Shift|z"] = {
    count = 0,
    key = "z",
    mods = "Mod4+Shift",
    desc = "centre floating window",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#16"] = {
    count = 0,
    key = "#16",
    mods = "Control+Mod4",
    desc = "toggle tag #7",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#18"] = {
    count = 0,
    key = "#18",
    mods = "Mod1+Mod4",
    desc = "toggle tag #9",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#11"] = {
    count = 0,
    key = "#11",
    mods = "Mod1+Mod4",
    desc = "toggle tag #2",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4+Shift|3"] = {
    count = 0,
    key = "3",
    mods = "Mod1+Mod4+Shift",
    desc = "character flicker shimmer mode",
    group = "shimmer",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#14"] = {
    count = 0,
    key = "#14",
    mods = "Mod4",
    desc = "view tag #5",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#15"] = {
    count = 0,
    key = "#15",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #6",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|k"] = {
    count = 0,
    key = "k",
    mods = "Control+Mod4",
    desc = "focus the previous screen",
    group = "screen",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#19"] = {
    count = 0,
    key = "#19",
    mods = "Mod4",
    desc = "view tag #10",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|r"] = {
    count = 7,
    key = "r",
    mods = "Control+Mod4",
    desc = "reload awesome",
    group = "awesome",
    first_seen = 1757158803,
    last_seen = 1757166725,
  },
  ["Mod4+Shift|#14"] = {
    count = 0,
    key = "#14",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #5",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|j"] = {
    count = 0,
    key = "j",
    mods = "Mod1+Mod4",
    desc = "rotate screens left",
    group = "screen",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#20"] = {
    count = 0,
    key = "#20",
    mods = "Control+Mod4",
    desc = "move client to tag #11",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|z"] = {
    count = 0,
    key = "z",
    mods = "Control+Mod4",
    desc = "media previous",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|j"] = {
    count = 0,
    key = "j",
    mods = "Mod4+Shift",
    desc = "swap with next client by index",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|Tab"] = {
    count = 3,
    key = "Tab",
    mods = "Mod4",
    desc = "go back",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757181085,
  },
  ["Mod4+Shift|F3"] = {
    count = 0,
    key = "F3",
    mods = "Mod4+Shift",
    desc = "run nicotine++",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|Return"] = {
    count = 0,
    key = "Return",
    mods = "Control+Mod4",
    desc = "move to master",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|n"] = {
    count = 3,
    key = "n",
    mods = "Mod4+Shift",
    desc = "jump to window",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757181114,
  },
  ["Control+Mod1+Mod4|b"] = {
    count = 0,
    key = "b",
    mods = "Control+Mod1+Mod4",
    desc = "Denon amp increase volume",
    group = "hardware",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#19"] = {
    count = 0,
    key = "#19",
    mods = "Control+Mod4+Shift",
    desc = "toggle client on tag #10",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#10"] = {
    count = 0,
    key = "#10",
    mods = "Control+Mod4",
    desc = "toggle tag #1",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|t"] = {
    count = 0,
    key = "t",
    mods = "Mod1+Mod4",
    desc = "tag chord: arrows to view/move tag (Shift to move)",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|F7"] = {
    count = 0,
    key = "F7",
    mods = "Mod4+Shift",
    desc = "run signal-desktop",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4+Shift|h"] = {
    count = 0,
    key = "h",
    mods = "Control+Mod1+Mod4+Shift",
    desc = "Move tag screen to the h",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod4+Shift|#12"] = {
    count = 0,
    key = "#12",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #3",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#10"] = {
    count = 0,
    key = "#10",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #1",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|m"] = {
    count = 0,
    key = "m",
    mods = "Control+Mod4",
    desc = "(un)maximize vertically",
    group = "client",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#18"] = {
    count = 0,
    key = "#18",
    mods = "Control+Mod4+Shift",
    desc = "toggle focused client on tag #9",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#17"] = {
    count = 0,
    key = "#17",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #8",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|p"] = {
    count = 0,
    key = "p",
    mods = "Mod1+Mod4",
    desc = "power rofi menu",
    group = "system",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4+Shift|#20"] = {
    count = 0,
    key = "#20",
    mods = "Control+Mod4+Shift",
    desc = "toggle client on tag #11",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4+Shift|0"] = {
    count = 0,
    key = "0",
    mods = "Mod1+Mod4+Shift",
    desc = "turn off shimmer",
    group = "shimmer",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Mod4|g"] = {
    count = 0,
    key = "g",
    mods = "Control+Mod1+Mod4",
    desc = "Denon amp decrease volume",
    group = "hardware",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|t"] = {
    count = 10,
    key = "t",
    mods = "Mod4",
    desc = "toggle keep on top",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757216013,
  },
  ["|XF86AudioNext"] = {
    count = 0,
    key = "XF86AudioNext",
    mods = "",
    desc = "media next",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|0"] = {
    count = 0,
    key = "0",
    mods = "Mod4",
    desc = "view tag #10",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#12"] = {
    count = 0,
    key = "#12",
    mods = "Mod4",
    desc = "view tag #3",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|#16"] = {
    count = 0,
    key = "#16",
    mods = "Mod4+Shift",
    desc = "move focused client to tag #7",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#13"] = {
    count = 0,
    key = "#13",
    mods = "Mod4",
    desc = "view tag #4",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#10"] = {
    count = 0,
    key = "#10",
    mods = "Mod4",
    desc = "view tag #1",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["|XF86AudioMute"] = {
    count = 0,
    key = "XF86AudioMute",
    mods = "",
    desc = "toggle mute",
    group = "hotkeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|#21"] = {
    count = 0,
    key = "#21",
    mods = "Mod4",
    desc = "view tag #12",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod4|#14"] = {
    count = 0,
    key = "#14",
    mods = "Control+Mod4",
    desc = "toggle tag #5",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|h"] = {
    count = 0,
    key = "h",
    mods = "Mod4+Shift",
    desc = "increase the number of master clients",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|l"] = {
    count = 3,
    key = "l",
    mods = "Mod4+Shift",
    desc = "decrease the number of master clients",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 1757163811,
  },
  ["Mod1+Mod4|#20"] = {
    count = 0,
    key = "#20",
    mods = "Mod1+Mod4",
    desc = "toggle tag #11",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|;"] = {
    count = 21,
    key = ";",
    mods = "Mod4",
    desc = "cycle minimized windows",
    group = "client",
    first_seen = 1757158803,
    last_seen = 1757206984,
  },
  ["Mod1+Mod4|h"] = {
    count = 0,
    key = "h",
    mods = "Mod1+Mod4",
    desc = "switch to horizontal treetile layout",
    group = "layout",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod1+Mod4|#13"] = {
    count = 0,
    key = "#13",
    mods = "Mod1+Mod4",
    desc = "toggle tag #4",
    group = "tag",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4|F12"] = {
    count = 4,
    key = "F12",
    mods = "Mod4",
    desc = "run Firefox",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 1757286960,
  },
  ["Mod4|v"] = {
    count = 35,
    key = "v",
    mods = "Mod4",
    desc = "toggle statusbar",
    group = "awesome",
    first_seen = 1757158803,
    last_seen = 1757283109,
  },
  ["|XF86AudioPrev"] = {
    count = 0,
    key = "XF86AudioPrev",
    mods = "",
    desc = "media previous",
    group = "mediakeys",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Control+Mod1+Shift|l"] = {
    count = 0,
    key = "l",
    mods = "Control+Mod1+Shift",
    desc = "Move tag to the l",
    group = "Collision",
    first_seen = 1757158805,
    last_seen = 0,
  },
  ["Mod1+Mod4|m"] = {
    count = 0,
    key = "m",
    mods = "Mod1+Mod4",
    desc = "monitor rofi menu",
    group = "system",
    first_seen = 1757158803,
    last_seen = 0,
  },
  ["Mod4+Shift|F2"] = {
    count = 0,
    key = "F2",
    mods = "Mod4+Shift",
    desc = "run Argodejo in a terminal",
    group = "launcher",
    first_seen = 1757158803,
    last_seen = 0,
  },
}
