-- plugins/floating_rules.lua
-- Dynamic floating window rules with persistent storage.
--
-- Replaces the old add-floating-rule.sh shell script that edited rc.lua
-- directly via awk. This module runs inside the WM process, so it can
-- access client.focus and ruled.client directly — no external process,
-- no file editing, no awk corruption risk.
--
-- Persistent rules live in a separate Lua data file (floating_rules_data.lua)
-- that this module reads on startup and writes when a new rule is added.
-- The in-memory rule_any table is the same reference passed to ruled.client,
-- so runtime additions take effect for future windows immediately without
-- re-registering the rule.

local awful = require("awful")
local ruled = require("ruled")
local naughty = require("naughty")

local M = {}

local CONFIG_DIR = os.getenv("HOME") .. "/.config/somewm"
local DATA_FILE = CONFIG_DIR .. "/floating_rules_data.lua"

local RULE_ID = "floating_dynamic"

-- Generic classes too broad to use as floating identifiers. When the
-- focused window's class matches one of these, fall back to instance,
-- role, or name instead (same list as the old shell script).
local generic_classes = {
    "Alacritty", "URxvt", "XTerm", "kitty", "st-256color", "foot", "wezterm", "WezTerm",
    "Chromium", "firefox", "Firefox", "Navigator", "Brave-browser", "Google-chrome", "Code",
    "mpv", "Vlc", "vlc", "Thunar", "Dolphin", "Nautilus", "Pcmanfm", "Emacs", "org.gnome.Nautilus",
}

local function is_generic_class(class)
    for _, g in ipairs(generic_classes) do
        if class == g then return true end
    end
    return false
end

-- Extract a stable substring from a window title so that name-based
-- rules match future windows from the same app, not just the current
-- title content. ruled.client matches name via Lua string.match (substring
-- pattern), so the extracted part matches any title containing it.
--
-- Heuristics (same as the old shell script):
--   "Page Title — App"  -> take after " — "  (browser-style app suffix)
--   "file.ext - App"    -> take after " - "  (editor-style app suffix)
--   "App: content"      -> take before ": "  (app prefix)
--   "Dialog Name"       -> keep as-is (likely already stable)
local function extract_stable_name(title)
    local segment = title:match(" — (.+)$")
    if segment and #segment >= 3 then return segment end
    segment = title:match(" - (.+)$")
    if segment and #segment >= 3 then return segment end
    segment = title:match("^(.-): ")
    if segment and #segment >= 3 then return segment end
    return title
end

-- The in-memory rule_any table. This same reference is passed to
-- ruled.client.append_rule, so inserting into the sub-tables at runtime
-- makes new entries visible to the rule matcher for future windows.
local rule_any = {
    class = {},
    instance = {},
    name = {},
    role = {},
}

local function load_data()
    local fn = loadfile(DATA_FILE)
    if not fn then
        return { class = {}, instance = {}, name = {}, role = {} }
    end
    local ok, data = pcall(fn)
    if not ok or type(data) ~= "table" then
        return { class = {}, instance = {}, name = {}, role = {} }
    end
    data.class = data.class or {}
    data.instance = data.instance or {}
    data.name = data.name or {}
    data.role = data.role or {}
    return data
end

local function escape_lua_string(s)
    return (s:gsub("\\", "\\\\"):gsub('"', '\\"'))
end

local function save_data()
    local f = io.open(DATA_FILE, "w")
    if not f then
        naughty.notification { message = "floating_rules: cannot write data file" }
        return false
    end
    f:write("-- auto-generated by plugins/floating_rules.lua\n")
    f:write("-- do not edit while somewm is running; additions via Super+Alt+F are persisted here\n")
    f:write("return {\n")
    f:write("    class = {")
    for _, v in ipairs(rule_any.class) do f:write(' "' .. escape_lua_string(v) .. '",') end
    f:write(" },\n")
    f:write("    instance = {")
    for _, v in ipairs(rule_any.instance) do f:write(' "' .. escape_lua_string(v) .. '",') end
    f:write(" },\n")
    f:write("    name = {")
    for _, v in ipairs(rule_any.name) do f:write(' "' .. escape_lua_string(v) .. '",') end
    f:write(" },\n")
    f:write("    role = {")
    for _, v in ipairs(rule_any.role) do f:write(' "' .. escape_lua_string(v) .. '",') end
    f:write(" },\n")
    f:write("}\n")
    f:close()
    return true
end

-- Register the dynamic floating rule. Call this from inside the
-- ruled.client "request::rules" signal handler in rc.lua, alongside
-- the other ruled.client.append_rule calls.
function M.register_rules()
    local data = load_data()
    -- copy entries into the in-memory tables (keeping the same table
    -- references that ruled.client holds)
    for _, v in ipairs(data.class) do table.insert(rule_any.class, v) end
    for _, v in ipairs(data.instance) do table.insert(rule_any.instance, v) end
    for _, v in ipairs(data.name) do table.insert(rule_any.name, v) end
    for _, v in ipairs(data.role) do table.insert(rule_any.role, v) end

    ruled.client.append_rule {
        id = RULE_ID,
        rule_any = rule_any,
        properties = {
            floating = true,
            placement = awful.placement.centered + awful.placement.no_overlap + awful.placement.no_offscreen,
        },
    }
end

-- Pick the most specific non-generic identifier from the focused client.
-- Returns type ("class"/"instance"/"role"/"name") and value, or nil.
local function choose_identifier(c)
    local class = c.class or ""
    local instance = c.instance or ""
    local name = c.name or ""
    local role = c.role or ""

    if class ~= "" and not is_generic_class(class) then
        return "class", class
    end
    if instance ~= "" then
        return "instance", instance
    end
    if role ~= "" then
        return "role", role
    end
    if name ~= "" then
        return "name", extract_stable_name(name)
    end
    return nil
end

local function already_present(list_type, value)
    for _, v in ipairs(rule_any[list_type]) do
        if v == value then return true end
    end
    return false
end

-- Add the focused window's identifier to the floating rules.
-- Called by the Super+Alt+F keybinding.
function M.add_focused()
    local c = client.focus
    if not c then
        naughty.notification { message = "floating_rules: no focused client" }
        return
    end

    local chosen_type, chosen_value = choose_identifier(c)
    if not chosen_value or chosen_value == "" then
        naughty.notification { message = "floating_rules: cannot determine identifier" }
        return
    end

    if already_present(chosen_type, chosen_value) then
        naughty.notification { message = string.format('already present: %s "%s"', chosen_type, chosen_value) }
        return
    end

    table.insert(rule_any[chosen_type], chosen_value)
    save_data()

    -- apply to the focused client immediately
    c.floating = true
    c.ontop = true

    naughty.notification { message = string.format('added %s="%s" to floating rules', chosen_type, chosen_value) }
end

return M
